// Generated by Sterling SDK Generator — test suite
// Orchestrator Control Plane API v0.1.0

package vers_sdk

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// captured holds details about the last request received by the test server.
type captured struct {
	Method string
	Path   string
	Body   string
}

func setupTestServer(t *testing.T) (*httptest.Server, *captured) {
	t.Helper()
	cap := &captured{}
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		cap.Method = r.Method
		cap.Path = r.URL.RequestURI()
		if r.Body != nil {
			bodyBytes, _ := io.ReadAll(r.Body)
			cap.Body = string(bodyBytes)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]string{"status": "ok"})
	}))
	return ts, cap
}

func setupErrorServer(t *testing.T, statusCode int) *httptest.Server {
	t.Helper()
	return httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(statusCode)
		_ = json.NewEncoder(w).Encode(map[string]string{"message": "error"})
	}))
}

func TestVmStatus_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VmStatus("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestResizeVmDisk_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ResizeVmDisk("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestExecVmStreamAttach_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ExecVmStreamAttach("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListVms_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListVms()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateNewRootVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateNewRootVm(nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestVmLogs_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VmLogs("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestBranchByRef_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.BranchByRef("test-id", "test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestLabelVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.LabelVm("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListPublicCommits_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListPublicCommits()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetImageStatus_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetImageStatus("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListPublicRepoTags_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListPublicRepoTags("test-id", "test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestVersionHandler_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VersionHandler()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestBranchByTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.BranchByTag("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetRepoTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetRepoTag("test-id", "test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteRepoTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteRepoTag("test-id", "test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUpdateRepoTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UpdateRepoTag("test-id", "test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestBranchVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.BranchVm("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetRepository_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetRepository("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteRepository_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteRepository("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListParentCommits_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListParentCommits("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestValidateKey_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ValidateKey(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestForkRepository_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ForkRepository(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListRepositories_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListRepositories()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateRepository_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateRepository(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUpdateVmState_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UpdateVmState("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateImage_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateImage(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestRestoreFromCommit_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.RestoreFromCommit(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetDomain_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetDomain("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteDomain_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteDomain("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListTags_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListTags()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateTag(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListPublicRepositories_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListPublicRepositories()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetPublicRepoTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetPublicRepoTag("test-id", "test-id", "test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetVmMetadata_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetVmMetadata("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListEnvVars_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListEnvVars()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestSetEnvVars_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.SetEnvVars(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PUT" {
		t.Errorf("method: got %s, want PUT", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteVm("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListCommits_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListCommits()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetTag("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteTag("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUpdateTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UpdateTag("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestBranchByVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.BranchByVm("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteEnvVar_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteEnvVar("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteImage_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteImage("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCommitVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CommitVm("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeleteCommit_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeleteCommit("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "DELETE" {
		t.Errorf("method: got %s, want DELETE", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUpdateCommit_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UpdateCommit("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListRepoTags_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListRepoTags("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateRepoTag_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateRepoTag("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestDeployHandler_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.DeployHandler(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestExecVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ExecVm("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestSetRepositoryVisibility_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.SetRepositoryVisibility("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PATCH" {
		t.Errorf("method: got %s, want PATCH", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestExecVmStream_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ExecVmStream("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListDomains_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListDomains(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestCreateDomain_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.CreateDomain(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestSshKey_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.SshKey("test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestListImages_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ListImages()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestReadFileVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.ReadFileVm("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestWriteFileVm_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.WriteFileVm("test-id", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "PUT" {
		t.Errorf("method: got %s, want PUT", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestUploadImage_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.UploadImage(nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestGetPublicRepository_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.GetPublicRepository("test-id", "test-id")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "GET" {
		t.Errorf("method: got %s, want GET", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestBranchByCommit_MethodAndPath(t *testing.T) {
	ts, cap := setupTestServer(t)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.BranchByCommit("test-id", nil, nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if cap.Method != "POST" {
		t.Errorf("method: got %s, want POST", cap.Method)
	}
	if !strings.HasPrefix(cap.Path, "/") {
		t.Errorf("path should start with /: got %s", cap.Path)
	}
}

func TestErrorHandling_400(t *testing.T) {
	ts := setupErrorServer(t, 400)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VmStatus("test-id")
	if err == nil {
		t.Fatal("expected error on 400")
	}
	var apiErr *APIError
	if ok := isAPIError(err, &apiErr); !ok {
		t.Fatalf("expected APIError, got %T", err)
	}
	if apiErr.Status != 400 {
		t.Errorf("status: got %d, want 400", apiErr.Status)
	}
}

func TestErrorHandling_404(t *testing.T) {
	ts := setupErrorServer(t, 404)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VmStatus("test-id")
	if err == nil {
		t.Fatal("expected error on 404")
	}
}

func TestErrorHandling_500(t *testing.T) {
	ts := setupErrorServer(t, 500)
	defer ts.Close()
	c := NewClient(ts.URL, "test-key")
	_, err := c.VmStatus("test-id")
	if err == nil {
		t.Fatal("expected error on 500")
	}
}

// isAPIError checks whether err is *APIError (via errors.As equivalent).
func isAPIError(err error, target **APIError) bool {
	if e, ok := err.(*APIError); ok {
		*target = e
		return true
	}
	return false
}
