// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package vers_sdk

import (
	"bytes"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"math"
	mrand "math/rand"
	"net/http"
	"net/url"
	"runtime"
	"os"
	"strconv"
	"strings"
	"time"
)

// LogLevel represents the SDK logging verbosity.
type LogLevel int

const (
	LogOff   LogLevel = 0
	LogError LogLevel = 1
	LogWarn  LogLevel = 2
	LogInfo  LogLevel = 3
	LogDebug LogLevel = 4
)

func parseLogLevel(s string) LogLevel {
	switch strings.ToLower(s) {
	case "debug":
		return LogDebug
	case "info":
		return LogInfo
	case "warn":
		return LogWarn
	case "error":
		return LogError
	case "off":
		return LogOff
	default:
		return LogWarn
	}
}

// RequestOptions provides per-request overrides for headers and timeout.
type RequestOptions struct {
	// Headers to merge with the request. Nil-valued entries are ignored.
	Headers map[string]string
	// Timeout overrides the client-level timeout when non-zero.
	Timeout time.Duration
}

type Client struct {
	BaseURL    string
	APIKey     string
	Headers    map[string]*string
	HTTPClient *http.Client
	MaxRetries int
	Timeout    time.Duration
	LogLevel   LogLevel
	Logger     *log.Logger
}

// mergeHeaders merges multiple header sources. Later sources override earlier ones
// using case-insensitive matching. A nil value removes the header.
func mergeHeaders(base http.Header, overrides ...map[string]*string) http.Header {
	merged := base.Clone()
	for _, src := range overrides {
		if src == nil {
			continue
		}
		for key, value := range src {
			canonical := http.CanonicalHeaderKey(key)
			if value == nil {
				merged.Del(canonical)
			} else {
				merged.Set(canonical, *value)
			}
		}
	}
	return merged
}

var retryableStatusCodes = map[int]bool{
	408: true,
	409: true,
	429: true,
}

func isRetryableStatus(code int) bool {
	return code >= 500 || retryableStatusCodes[code]
}

func retryDelay(attempt int) time.Duration {
	baseMs := 500.0 * math.Pow(2, float64(attempt))
	jitterMs := mrand.Float64() * baseMs * 0.25
	return time.Duration(baseMs+jitterMs) * time.Millisecond
}

func parseRetryAfter(headerValue string) (time.Duration, bool) {
	if headerValue == "" {
		return 0, false
	}
	if seconds, err := strconv.Atoi(headerValue); err == nil {
		d := time.Duration(seconds) * time.Second
		if d < 0 {
			d = 0
		}
		if d > 60*time.Second {
			d = 60 * time.Second
		}
		return d, true
	}
	if t, err := time.Parse(time.RFC1123, headerValue); err == nil {
		d := time.Until(t)
		if d < 0 {
			d = 0
		}
		if d > 60*time.Second {
			d = 60 * time.Second
		}
		return d, true
	}
	return 0, false
}

// ClientOption is a functional option for configuring the Client.
type ClientOption func(*Client)

// WithHTTPClient sets a custom *http.Client for the SDK client.
func WithHTTPClient(hc *http.Client) ClientOption {
	return func(c *Client) {
		c.HTTPClient = hc
	}
}

func NewClient(baseURL string, apiKey string, opts ...ClientOption) *Client {
	if baseURL == "" {
		if envURL := os.Getenv("VERS_BASE_URL"); envURL != "" {
			baseURL = envURL
		}
	}
	if apiKey == "" {
		if envKey := os.Getenv("VERS_API_KEY"); envKey != "" {
			apiKey = envKey
		}
	}
	envLogLevel := parseLogLevel(os.Getenv("VERS_LOG"))
	c := &Client{
		BaseURL:    baseURL,
		APIKey:     apiKey,
		Headers:    nil,
		HTTPClient: &http.Client{},
		MaxRetries: 2,
		Timeout:    30 * time.Second,
		LogLevel:   envLogLevel,
		Logger:     log.New(os.Stderr, "[vers_sdk] ", log.LstdFlags),
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Client) logf(level LogLevel, format string, args ...interface{}) {
	if c.LogLevel >= level && c.Logger != nil {
		c.Logger.Printf(format, args...)
	}
}

func isMutatingMethod(method string) bool {
	switch strings.ToUpper(method) {
	case "POST", "PUT", "PATCH", "DELETE":
		return true
	}
	return false
}

func generateIdempotencyKey() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

func (c *Client) doRequest(method, path string, body interface{}, opts ...*RequestOptions) (*http.Response, error) {
	var opt *RequestOptions
	for _, o := range opts {
		if o != nil {
			opt = o
			break
		}
	}
	c.logf(LogDebug, "request: %s %s", method, path)
	idempotencyKey := ""
	if isMutatingMethod(method) {
		idempotencyKey = generateIdempotencyKey()
	}
	var lastErr error
	retryAfterUsed := false
	for attempt := 0; attempt <= c.MaxRetries; attempt++ {
		if attempt > 0 && !retryAfterUsed {
			c.logf(LogInfo, "retry attempt %d/%d for %s %s", attempt, c.MaxRetries, method, path)
			time.Sleep(retryDelay(attempt - 1))
		}
		retryAfterUsed = false

		var reqBody io.Reader
		if body != nil {
			jsonBody, err := json.Marshal(body)
			if err != nil {
				return nil, fmt.Errorf("marshal body: %w", err)
			}
			reqBody = bytes.NewBuffer(jsonBody)
		}
		req, err := http.NewRequest(method, c.BaseURL+path, reqBody)
		if err != nil {
			return nil, fmt.Errorf("create request: %w", err)
		}
		defaultHeaders := make(http.Header)
		defaultHeaders.Set("Content-Type", "application/json")
		defaultHeaders.Set("User-Agent", fmt.Sprintf("vers-sdk/0.1.8 go/%s %s/%s", runtime.Version(), runtime.GOOS, runtime.GOARCH))
		if c.APIKey != "" {
			defaultHeaders.Set("Authorization", "Bearer "+c.APIKey)
		}
		if idempotencyKey != "" {
			defaultHeaders.Set("X-Idempotency-Key", idempotencyKey)
		}
		req.Header = mergeHeaders(defaultHeaders, c.Headers)
		// Apply per-request header overrides
		if opt != nil {
			for k, v := range opt.Headers {
				req.Header.Set(k, v)
			}
		}

		effectiveTimeout := c.Timeout
		if opt != nil && opt.Timeout > 0 {
			effectiveTimeout = opt.Timeout
		}
		client := c.HTTPClient
		if client.Timeout == 0 && effectiveTimeout > 0 {
			client = &http.Client{Timeout: effectiveTimeout}
		}
		resp, err := client.Do(req)
		if err != nil {
			c.logf(LogError, "connection error: %s %s - %v", method, path, err)
			lastErr = &ConnectionError{Message: err.Error(), Cause: err}
			if attempt == c.MaxRetries {
				return nil, lastErr
			}
			continue
		}
		c.logf(LogDebug, "response: %d for %s %s", resp.StatusCode, method, path)
		if isRetryableStatus(resp.StatusCode) && attempt < c.MaxRetries {
			if d, ok := parseRetryAfter(resp.Header.Get("Retry-After")); ok {
				retryAfterUsed = true
				c.logf(LogInfo, "retry attempt %d/%d for %s %s (retry-after: %v)", attempt+1, c.MaxRetries, method, path, d)
				time.Sleep(d)
			}
			resp.Body.Close()
			lastErr = fmt.Errorf("HTTP %d", resp.StatusCode)
			continue
		}
		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			defer resp.Body.Close()
			bodyBytes, _ := io.ReadAll(resp.Body)
			return nil, NewAPIError(resp.StatusCode, resp.Header, string(bodyBytes))
		}
		return resp, nil
	}
	return nil, lastErr
}

// VmStatus - 
func (c *Client) VmStatus(vm_id string, opts ...*RequestOptions) (*VM, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/status", vm_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VM
		return &empty, nil
	}
	var result VM
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ResizeVmDisk - 
func (c *Client) ResizeVmDisk(vm_id string, body interface{}, params *ResizeVmDiskParams, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/disk", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ExecVmStreamAttach - 
func (c *Client) ExecVmStreamAttach(vm_id string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/exec/stream/attach", vm_id)
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ListVms - 
func (c *Client) ListVms(opts ...*RequestOptions) ([]VM, error) {
	reqPath := "/api/v1/vms"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return nil, nil
	}
	var result []VM
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// CreateNewRootVm - 
func (c *Client) CreateNewRootVm(body interface{}, params *CreateNewRootVmParams, opts ...*RequestOptions) (*NewVmResponse, error) {
	reqPath := "/api/v1/vm/new_root"
	qp := url.Values{}
	if params != nil {
		if params.WaitBoot != nil {
			qp.Set("wait_boot", fmt.Sprintf("%v", *params.WaitBoot))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmResponse
		return &empty, nil
	}
	var result NewVmResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// VmLogs - 
func (c *Client) VmLogs(vm_id string, params *VmLogsParams, opts ...*RequestOptions) (*VmExecLogResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/logs", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.Offset != nil {
			qp.Set("offset", fmt.Sprintf("%v", *params.Offset))
		}
		if params.MaxEntries != nil {
			qp.Set("max_entries", fmt.Sprintf("%v", *params.MaxEntries))
		}
		if params.Stream != nil {
			qp.Set("stream", fmt.Sprintf("%v", *params.Stream))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmExecLogResponse
		return &empty, nil
	}
	var result VmExecLogResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// BranchByRef - 
func (c *Client) BranchByRef(repo_name string, tag_name string, body interface{}, params *BranchByRefParams, opts ...*RequestOptions) (*NewVmsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/branch/by_ref/%s/%s", repo_name, tag_name)
	qp := url.Values{}
	if params != nil {
		if params.Count != nil {
			qp.Set("count", fmt.Sprintf("%v", *params.Count))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmsResponse
		return &empty, nil
	}
	var result NewVmsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// LabelVm - 
func (c *Client) LabelVm(vm_id string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/label", vm_id)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ListPublicCommits - 
func (c *Client) ListPublicCommits(opts ...*RequestOptions) (*ListCommitsResponse, error) {
	reqPath := "/api/v1/commits/public"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListCommitsResponse
		return &empty, nil
	}
	var result ListCommitsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetImageStatus - 
func (c *Client) GetImageStatus(image_name string, opts ...*RequestOptions) (*BaseImageStatusResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/images/%s/status", image_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty BaseImageStatusResponse
		return &empty, nil
	}
	var result BaseImageStatusResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListPublicRepoTags - 
func (c *Client) ListPublicRepoTags(org_name string, repo_name string, opts ...*RequestOptions) (*ListRepoTagsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/public/repositories/%s/%s/tags", org_name, repo_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListRepoTagsResponse
		return &empty, nil
	}
	var result ListRepoTagsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// VersionHandler - 
func (c *Client) VersionHandler(opts ...*RequestOptions) (*OrchestratorVersion, error) {
	reqPath := "/api/v1/system/version"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty OrchestratorVersion
		return &empty, nil
	}
	var result OrchestratorVersion
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// BranchByTag - 
func (c *Client) BranchByTag(tag_name string, body interface{}, params *BranchByTagParams, opts ...*RequestOptions) (*NewVmsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/branch/by_tag/%s", tag_name)
	qp := url.Values{}
	if params != nil {
		if params.Count != nil {
			qp.Set("count", fmt.Sprintf("%v", *params.Count))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmsResponse
		return &empty, nil
	}
	var result NewVmsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetRepoTag - 
func (c *Client) GetRepoTag(repo_name string, tag_name string, opts ...*RequestOptions) (*RepoTagInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty RepoTagInfo
		return &empty, nil
	}
	var result RepoTagInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteRepoTag - 
func (c *Client) DeleteRepoTag(repo_name string, tag_name string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// UpdateRepoTag - 
func (c *Client) UpdateRepoTag(repo_name string, tag_name string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/tags/%s", repo_name, tag_name)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// BranchVm - 
func (c *Client) BranchVm(vm_or_commit_id string, body interface{}, params *BranchVmParams, opts ...*RequestOptions) (*NewVmsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/branch", vm_or_commit_id)
	qp := url.Values{}
	if params != nil {
		if params.KeepPaused != nil {
			qp.Set("keep_paused", fmt.Sprintf("%v", *params.KeepPaused))
		}
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
		if params.Count != nil {
			qp.Set("count", fmt.Sprintf("%v", *params.Count))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmsResponse
		return &empty, nil
	}
	var result NewVmsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetRepository - 
func (c *Client) GetRepository(repo_name string, opts ...*RequestOptions) (*RepositoryInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s", repo_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty RepositoryInfo
		return &empty, nil
	}
	var result RepositoryInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteRepository - 
func (c *Client) DeleteRepository(repo_name string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s", repo_name)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ListParentCommits - 
func (c *Client) ListParentCommits(commit_id string, opts ...*RequestOptions) ([]VmCommitEntity, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/commits/%s/parents", commit_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return nil, nil
	}
	var result []VmCommitEntity
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ValidateKey - 
func (c *Client) ValidateKey(body interface{}, opts ...*RequestOptions) (*ValidateKeyResponse, error) {
	reqPath := "/api/v1/keys/validate"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ValidateKeyResponse
		return &empty, nil
	}
	var result ValidateKeyResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ForkRepository - 
func (c *Client) ForkRepository(body interface{}, opts ...*RequestOptions) (*ForkRepositoryResponse, error) {
	reqPath := "/api/v1/repositories/fork"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ForkRepositoryResponse
		return &empty, nil
	}
	var result ForkRepositoryResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListRepositories - 
func (c *Client) ListRepositories(opts ...*RequestOptions) (*ListRepositoriesResponse, error) {
	reqPath := "/api/v1/repositories"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListRepositoriesResponse
		return &empty, nil
	}
	var result ListRepositoriesResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CreateRepository - 
func (c *Client) CreateRepository(body interface{}, opts ...*RequestOptions) (*CreateRepositoryResponse, error) {
	reqPath := "/api/v1/repositories"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty CreateRepositoryResponse
		return &empty, nil
	}
	var result CreateRepositoryResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// UpdateVmState - 
func (c *Client) UpdateVmState(vm_id string, body interface{}, params *UpdateVmStateParams, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/state", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// CreateImage - 
func (c *Client) CreateImage(body interface{}, opts ...*RequestOptions) (*CreateBaseImageResponse, error) {
	reqPath := "/api/v1/images/create"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty CreateBaseImageResponse
		return &empty, nil
	}
	var result CreateBaseImageResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// RestoreFromCommit - 
func (c *Client) RestoreFromCommit(body interface{}, opts ...*RequestOptions) (*NewVmResponse, error) {
	reqPath := "/api/v1/vm/from_commit"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmResponse
		return &empty, nil
	}
	var result NewVmResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetDomain - 
func (c *Client) GetDomain(domain_id string, opts ...*RequestOptions) (*DomainResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/domains/%s", domain_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty DomainResponse
		return &empty, nil
	}
	var result DomainResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteDomain - 
func (c *Client) DeleteDomain(domain_id string, opts ...*RequestOptions) (*DeleteDomainResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/domains/%s", domain_id)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty DeleteDomainResponse
		return &empty, nil
	}
	var result DeleteDomainResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListTags - 
func (c *Client) ListTags(opts ...*RequestOptions) (*ListTagsResponse, error) {
	reqPath := "/api/v1/commit_tags"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListTagsResponse
		return &empty, nil
	}
	var result ListTagsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CreateTag - 
func (c *Client) CreateTag(body interface{}, opts ...*RequestOptions) (*CreateTagResponse, error) {
	reqPath := "/api/v1/commit_tags"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty CreateTagResponse
		return &empty, nil
	}
	var result CreateTagResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListPublicRepositories - 
func (c *Client) ListPublicRepositories(opts ...*RequestOptions) (*ListPublicRepositoriesResponse, error) {
	reqPath := "/api/v1/public/repositories"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListPublicRepositoriesResponse
		return &empty, nil
	}
	var result ListPublicRepositoriesResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetPublicRepoTag - 
func (c *Client) GetPublicRepoTag(org_name string, repo_name string, tag_name string, opts ...*RequestOptions) (*RepoTagInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/public/repositories/%s/%s/tags/%s", org_name, repo_name, tag_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty RepoTagInfo
		return &empty, nil
	}
	var result RepoTagInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetVmMetadata - 
func (c *Client) GetVmMetadata(vm_id string, opts ...*RequestOptions) (*VmMetadataResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/metadata", vm_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmMetadataResponse
		return &empty, nil
	}
	var result VmMetadataResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListEnvVars - 
func (c *Client) ListEnvVars(opts ...*RequestOptions) (*EnvVarsResponse, error) {
	reqPath := "/api/v1/env_vars"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty EnvVarsResponse
		return &empty, nil
	}
	var result EnvVarsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// SetEnvVars - 
func (c *Client) SetEnvVars(body interface{}, opts ...*RequestOptions) (*EnvVarsResponse, error) {
	reqPath := "/api/v1/env_vars"
	resp, err := c.doRequest("PUT", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty EnvVarsResponse
		return &empty, nil
	}
	var result EnvVarsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteVm - 
func (c *Client) DeleteVm(vm_id string, params *DeleteVmParams, opts ...*RequestOptions) (*VmDeleteResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmDeleteResponse
		return &empty, nil
	}
	var result VmDeleteResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListCommits - 
func (c *Client) ListCommits(opts ...*RequestOptions) (*ListCommitsResponse, error) {
	reqPath := "/api/v1/commits"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListCommitsResponse
		return &empty, nil
	}
	var result ListCommitsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetTag - 
func (c *Client) GetTag(tag_name string, opts ...*RequestOptions) (*TagInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/commit_tags/%s", tag_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty TagInfo
		return &empty, nil
	}
	var result TagInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteTag - 
func (c *Client) DeleteTag(tag_name string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/commit_tags/%s", tag_name)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// UpdateTag - 
func (c *Client) UpdateTag(tag_name string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/commit_tags/%s", tag_name)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// BranchByVm - 
func (c *Client) BranchByVm(vm_id string, body interface{}, params *BranchByVmParams, opts ...*RequestOptions) (*NewVmsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/branch/by_vm/%s", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.KeepPaused != nil {
			qp.Set("keep_paused", fmt.Sprintf("%v", *params.KeepPaused))
		}
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
		if params.Count != nil {
			qp.Set("count", fmt.Sprintf("%v", *params.Count))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmsResponse
		return &empty, nil
	}
	var result NewVmsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteEnvVar - 
func (c *Client) DeleteEnvVar(key string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/env_vars/%s", key)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// DeleteImage - 
func (c *Client) DeleteImage(base_image_id string, opts ...*RequestOptions) (*DeleteBaseImageResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/images/images/%s", base_image_id)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty DeleteBaseImageResponse
		return &empty, nil
	}
	var result DeleteBaseImageResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CommitVm - 
func (c *Client) CommitVm(vm_id string, body interface{}, params *CommitVmParams, opts ...*RequestOptions) (*VmCommitResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/commit", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.KeepPaused != nil {
			qp.Set("keep_paused", fmt.Sprintf("%v", *params.KeepPaused))
		}
		if params.SkipWaitBoot != nil {
			qp.Set("skip_wait_boot", fmt.Sprintf("%v", *params.SkipWaitBoot))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmCommitResponse
		return &empty, nil
	}
	var result VmCommitResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeleteCommit - 
func (c *Client) DeleteCommit(commit_id string, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/commits/%s", commit_id)
	resp, err := c.doRequest("DELETE", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// UpdateCommit - 
func (c *Client) UpdateCommit(commit_id string, body interface{}, opts ...*RequestOptions) (*CommitInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/commits/%s", commit_id)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty CommitInfo
		return &empty, nil
	}
	var result CommitInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListRepoTags - 
func (c *Client) ListRepoTags(repo_name string, opts ...*RequestOptions) (*ListRepoTagsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/tags", repo_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListRepoTagsResponse
		return &empty, nil
	}
	var result ListRepoTagsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// CreateRepoTag - 
func (c *Client) CreateRepoTag(repo_name string, body interface{}, opts ...*RequestOptions) (*CreateRepoTagResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/tags", repo_name)
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty CreateRepoTagResponse
		return &empty, nil
	}
	var result CreateRepoTagResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// DeployHandler - Deploy a GitHub repository to a new Vers project.
func (c *Client) DeployHandler(body interface{}, opts ...*RequestOptions) (*DeployResponse, error) {
	reqPath := "/api/v1/deploy"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty DeployResponse
		return &empty, nil
	}
	var result DeployResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ExecVm - 
func (c *Client) ExecVm(vm_id string, body interface{}, opts ...*RequestOptions) (*VmExecResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/exec", vm_id)
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmExecResponse
		return &empty, nil
	}
	var result VmExecResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// SetRepositoryVisibility - 
func (c *Client) SetRepositoryVisibility(repo_name string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/repositories/%s/visibility", repo_name)
	resp, err := c.doRequest("PATCH", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ExecVmStream - 
func (c *Client) ExecVmStream(vm_id string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/exec/stream", vm_id)
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// ListDomains - 
func (c *Client) ListDomains(params *ListDomainsParams, opts ...*RequestOptions) ([]DomainResponse, error) {
	reqPath := "/api/v1/domains"
	qp := url.Values{}
	if params != nil {
		if params.VmId != nil {
			qp.Set("vm_id", fmt.Sprintf("%v", *params.VmId))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return nil, nil
	}
	var result []DomainResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// CreateDomain - 
func (c *Client) CreateDomain(body interface{}, opts ...*RequestOptions) (*DomainResponse, error) {
	reqPath := "/api/v1/domains"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty DomainResponse
		return &empty, nil
	}
	var result DomainResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// SshKey - 
func (c *Client) SshKey(vm_id string, opts ...*RequestOptions) (*VmSshKeyResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/ssh_key", vm_id)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmSshKeyResponse
		return &empty, nil
	}
	var result VmSshKeyResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ListImages - 
func (c *Client) ListImages(opts ...*RequestOptions) (*ListBaseImagesResponse, error) {
	reqPath := "/api/v1/images"
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty ListBaseImagesResponse
		return &empty, nil
	}
	var result ListBaseImagesResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// ReadFileVm - 
func (c *Client) ReadFileVm(vm_id string, params *ReadFileVmParams, opts ...*RequestOptions) (*VmReadFileResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/files", vm_id)
	qp := url.Values{}
	if params != nil {
		if params.Path != nil {
			qp.Set("path", fmt.Sprintf("%v", *params.Path))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty VmReadFileResponse
		return &empty, nil
	}
	var result VmReadFileResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// WriteFileVm - 
func (c *Client) WriteFileVm(vm_id string, body interface{}, opts ...*RequestOptions) (map[string]interface{}, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/%s/files", vm_id)
	resp, err := c.doRequest("PUT", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		return map[string]interface{}{}, nil
	}
	var result map[string]interface{}
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return result, nil
}

// UploadImage - 
func (c *Client) UploadImage(body interface{}, opts ...*RequestOptions) (*UploadBaseImageResponse, error) {
	reqPath := "/api/v1/images/upload"
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty UploadBaseImageResponse
		return &empty, nil
	}
	var result UploadBaseImageResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// GetPublicRepository - 
func (c *Client) GetPublicRepository(org_name string, repo_name string, opts ...*RequestOptions) (*PublicRepositoryInfo, error) {
	reqPath := fmt.Sprintf("/api/v1/public/repositories/%s/%s", org_name, repo_name)
	resp, err := c.doRequest("GET", reqPath, nil, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty PublicRepositoryInfo
		return &empty, nil
	}
	var result PublicRepositoryInfo
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

// BranchByCommit - 
func (c *Client) BranchByCommit(commit_id string, body interface{}, params *BranchByCommitParams, opts ...*RequestOptions) (*NewVmsResponse, error) {
	reqPath := fmt.Sprintf("/api/v1/vm/branch/by_commit/%s", commit_id)
	qp := url.Values{}
	if params != nil {
		if params.Count != nil {
			qp.Set("count", fmt.Sprintf("%v", *params.Count))
		}
	}
	if qs := qp.Encode(); qs != "" {
		reqPath += "?" + qs
	}
	resp, err := c.doRequest("POST", reqPath, body, opts...)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}
	if len(bodyBytes) == 0 {
		var empty NewVmsResponse
		return &empty, nil
	}
	var result NewVmsResponse
	if err := json.Unmarshal(bodyBytes, &result); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}
	return &result, nil
}

