// Generated by Sterling SDK Generator
// Orchestrator Control Plane API v0.1.0

package vers_sdk

// Response body for GET /env_vars and PUT /env_vars.
type EnvVarsResponse struct {
	// All environment variables currently set for the authenticated user.
	Vars map[string]string `json:"vars"`
}

// Response body for POST /api/v1/repositories
type CreateRepositoryResponse struct {
	// The name of the repository
	Name string `json:"name"`
	// The ID of the newly created repository
	RepoId string `json:"repo_id"`
}

// Public repository information (includes owner org name for namespacing)
type PublicRepositoryInfo struct {
	// When the repository was created
	CreatedAt string `json:"created_at"`
	// Optional description
	Description string `json:"description,omitempty"`
	// Full reference: org_name/repo_name
	FullName string `json:"full_name"`
	// The repository name
	Name string `json:"name"`
	// The owning organization's name (namespace)
	OrgName string `json:"org_name"`
	// The repository's unique identifier
	RepoId string `json:"repo_id"`
}

// 
type WhoamiOrg struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

// Response body for GET /api/v1/commit_tags
type ListTagsResponse struct {
	// List of all tags in the user's organization
	Tags []TagInfo `json:"tags"`
}

// Request body for creating a tag within a repository: POST /api/v1/repositories/{repo_name}/tags
type CreateRepoTagRequest struct {
	// The commit ID this tag should point to
	CommitId string `json:"commit_id"`
	// Optional description of what this tag represents
	Description string `json:"description,omitempty"`
	// The tag name (e.g. 'latest', 'v1.0')
	TagName string `json:"tag_name"`
}

// Response struct for GET api/v1/system/version
type OrchestratorVersion struct {
	// Executable identifier; should be 'orchestrator'
	ExecutableName string `json:"executable_name"`
	// Current git hash used for the build
	GitHash string `json:"git_hash"`
	// Current workspace version
	WorkspaceVersion string `json:"workspace_version"`
}

// 
type WhoamiApiKey struct {
	CreatedAt string `json:"created_at"`
	ExpiresAt string `json:"expires_at,omitempty"`
	Id string `json:"id"`
	Label string `json:"label"`
	MaxMemoryMib int64 `json:"max_memory_mib,omitempty"`
	MaxVcpus int32 `json:"max_vcpus,omitempty"`
}

// Request body for POST /vm/{vm_id}/commit
type CommitVmRequest struct {
	// Optional description for the commit.
	Description string `json:"description,omitempty"`
	// Optional human-readable name for the commit. Defaults to auto-generated name if not provided.
	Name string `json:"name,omitempty"`
}

// 
type ListCommitsResponse struct {
	Commits []CommitInfo `json:"commits"`
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total int64 `json:"total"`
}

// Response body for `POST /api/v1/deploy`.
type DeployResponse struct {
	ProjectId string `json:"project_id"`
	Status string `json:"status"`
	VmId string `json:"vm_id"`
}

// Response body for GET /api/v1/repositories/{repo_name}/tags
type ListRepoTagsResponse struct {
	// The repository name
	Repository string `json:"repository"`
	// List of tags in this repository
	Tags []RepoTagInfo `json:"tags"`
}

// 
type BaseImageInfo struct {
	BaseImageId string `json:"base_image_id"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description,omitempty"`
	ImageName string `json:"image_name"`
	IsPublic bool `json:"is_public"`
	OwnerId string `json:"owner_id"`
	SizeMib int32 `json:"size_mib"`
	SourceType string `json:"source_type"`
}

// Response body for POST /api/vm/{vm_id}/exec
type VmExecResponse struct {
	// Exec identifier associated with this run.
	ExecId string `json:"exec_id,omitempty"`
	// Exit code returned by the command.
	ExitCode int32 `json:"exit_code"`
	// UTF-8 decoded stderr (lossy).
	Stderr string `json:"stderr"`
	// UTF-8 decoded stdout (lossy).
	Stdout string `json:"stdout"`
}

// 
type CreateBaseImageResponse struct {
	ImageName string `json:"image_name"`
	JobId string `json:"job_id"`
	Status string `json:"status"`
}

// Request body for POST /api/vm/{vm_id}/exec
type VmExecRequest struct {
	// Command and arguments to execute.
	Command []string `json:"command"`
	// Optional environment variables to set for the process.
	Env map[string]string `json:"env,omitempty"`
	// Optional exec identifier for tracking.
	ExecId string `json:"exec_id,omitempty"`
	// Optional stdin payload passed to the command.
	Stdin string `json:"stdin,omitempty"`
	// Timeout in seconds (0 = no timeout).
	TimeoutSecs int64 `json:"timeout_secs,omitempty"`
	// Optional working directory for the command.
	WorkingDir string `json:"working_dir,omitempty"`
}

// 
type NewVmsResponse struct {
	Vms []NewVmResponse `json:"vms"`
}

// Request body for POST /api/vm/{vm_id}/exec/stream/attach
type VmExecStreamAttachRequest struct {
	// Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed.
	Cursor int64 `json:"cursor,omitempty"`
	// Identifier of the exec stream session to reattach to.
	ExecId string `json:"exec_id"`
	// Start streaming after the latest retained chunk (ignores cursor).
	FromLatest bool `json:"from_latest,omitempty"`
}

// Request body for PATCH /api/vm/{vm_id}/state
type VmUpdateStateRequest struct {
	// The requested state for the VM
	State VmUpdateStateEnum `json:"state"`
}

// 
type DeleteBaseImageResponse struct {
	BaseImageId string `json:"base_image_id"`
	Deleted bool `json:"deleted"`
}

// Response body for GET /api/v1/public/repositories
type ListPublicRepositoriesResponse struct {
	Repositories []PublicRepositoryInfo `json:"repositories"`
}

// Request body for POST /api/v1/commit_tags
type CreateTagRequest struct {
	// The commit ID this tag should point to
	CommitId string `json:"commit_id"`
	// Optional description of what this tag represents
	Description string `json:"description,omitempty"`
	// The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars)
	TagName string `json:"tag_name"`
}

// Response body for GET /api/v1/repositories
type ListRepositoriesResponse struct {
	// List of all repositories in the user's organization
	Repositories []RepositoryInfo `json:"repositories"`
}

// Response body for POST /api/v1/repositories/{repo_name}/tags
type CreateRepoTagResponse struct {
	// The commit ID this tag points to
	CommitId string `json:"commit_id"`
	// Full reference in image_name:tag format
	Reference string `json:"reference"`
	// The ID of the newly created tag
	TagId string `json:"tag_id"`
}

// 
type CommitInfo struct {
	CommitId string `json:"commit_id"`
	CreatedAt string `json:"created_at"`
	Description string `json:"description,omitempty"`
	GrandparentCommitId string `json:"grandparent_commit_id,omitempty"`
	IsPublic bool `json:"is_public"`
	Name string `json:"name"`
	OwnerId string `json:"owner_id"`
	ParentVmId string `json:"parent_vm_id,omitempty"`
}

// Response body for DELETE /api/v1/domains/{domain_id}
type DeleteDomainResponse struct {
	DomainId string `json:"domain_id"`
}

// Repository information returned in list and get operations
type RepositoryInfo struct {
	// When the repository was created
	CreatedAt string `json:"created_at"`
	// Optional description
	Description string `json:"description,omitempty"`
	// Whether this repository is publicly visible
	IsPublic bool `json:"is_public"`
	// The repository name
	Name string `json:"name"`
	// The repository's unique identifier
	RepoId string `json:"repo_id"`
}

// Response body for POST /api/keys/validate
type ValidateKeyResponse struct {
	Message string `json:"message"`
	Valid bool `json:"valid"`
}

// Response body for GET /api/vm/{vm_id}/ssh_key
type VmSshKeyResponse struct {
	// The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device)
	SshPort int32 `json:"ssh_port"`
	// Private SSH key in stringified OpenSSH format
	SshPrivateKey string `json:"ssh_private_key"`
}

// The state of a VM
type VmState string

const (
	VmStateBooting VmState = "booting"
	VmStateRunning VmState = "running"
	VmStatePaused VmState = "paused"
	VmStateSleeping VmState = "sleeping"
	VmStateDead VmState = "dead"
)

// Response body for GET /api/vm/{vm_id}/files
type VmReadFileResponse struct {
	// File contents, base64-encoded.
	ContentB64 string `json:"content_b64"`
}

// Request body for PUT /env_vars — sets (upserts) one or more environment variables.  # Lifecycle model  Environment variables are written to `/etc/environment` inside a VM **once at boot time** via a vsock `WriteFile` request. They are **not** live-synced to running VMs. This is intentional: VMs are ephemeral (create → use → destroy/branch), so env var changes naturally take effect on the next VM.  The `replace` flag exists so callers can atomically express 'I want exactly these variables and nothing else' without having to DELETE each stale key individually. Without it, the only way to remove a variable from future VMs is a separate `DELETE /env_vars/{key}` call per key.
type SetEnvVarsRequest struct {
	// If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert).
	Replace bool `json:"replace,omitempty"`
	// Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics).
	Vars map[string]string `json:"vars"`
}

// The response body for POST /api/vm/{vm_id}/commit
type VmCommitResponse struct {
	// The UUID of the newly-created commit
	CommitId string `json:"commit_id"`
}

// Response body for POST /api/v1/repositories/fork
type ForkRepositoryResponse struct {
	// The new commit in your org (snapshot of the forked VM)
	CommitId string `json:"commit_id"`
	// Full reference: repo_name:tag_name
	Reference string `json:"reference"`
	// The new repository name in your org
	RepoName string `json:"repo_name"`
	// The tag name pointing to the forked commit
	TagName string `json:"tag_name"`
	// The new VM that was created from the fork
	VmId string `json:"vm_id"`
}

// 
// This is a union type — exactly one field should be set.
type ImageSourceRequest struct {
	ImageRef *string `json:"image_ref,omitempty"`
	Type *string `json:"type,omitempty"`
	Bucket *string `json:"bucket,omitempty"`
	Key *string `json:"key,omitempty"`
	Type *string `json:"type,omitempty"`
}

// Possible options for the state requested in PATCH /api/vm/{vm_id}/state
type VmUpdateStateEnum string

const (
	VmUpdateStateEnumSleeping VmUpdateStateEnum = "Sleeping"
	VmUpdateStateEnumRunning VmUpdateStateEnum = "Running"
)

// 
type ErrorResponse struct {
	// Reason of error
	Error string `json:"error,omitempty"`
	// Is always: false
	Success bool `json:"success,omitempty"`
}

// Request body for PATCH /commits/{commit_id}
type UpdateCommitRequest struct {
	// Optional description for the commit.
	Description string `json:"description,omitempty"`
	IsPublic bool `json:"is_public"`
	// Optional human-readable name for the commit.
	Name string `json:"name,omitempty"`
}

// Request body for POST /api/v1/repositories
type CreateRepositoryRequest struct {
	// Optional description of the repository
	Description string `json:"description,omitempty"`
	// The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars)
	Name string `json:"name"`
}

// Response type for domain operations.
type DomainResponse struct {
	CreatedAt string `json:"created_at"`
	Domain string `json:"domain"`
	DomainId string `json:"domain_id"`
	VmId string `json:"vm_id"`
}

// Settings for the deploy build pipeline.
type DeploySettings struct {
	BuildCommand string `json:"build_command,omitempty"`
	InstallCommand string `json:"install_command,omitempty"`
	RunCommand string `json:"run_command,omitempty"`
	WorkingDirectory string `json:"working_directory,omitempty"`
}

// 
type CreateBaseImageRequest struct {
	Description string `json:"description,omitempty"`
	ImageName string `json:"image_name"`
	// Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space.
	SizeMib int32 `json:"size_mib,omitempty"`
	Source ImageSourceRequest `json:"source"`
}

// Request body for POST /api/v1/repositories/fork
type ForkRepositoryRequest struct {
	// Name for the new repository in your org (defaults to source_repo if omitted)
	RepoName string `json:"repo_name,omitempty"`
	// The organization that owns the source public repository
	SourceOrg string `json:"source_org"`
	// The source repository name
	SourceRepo string `json:"source_repo"`
	// The tag to fork (e.g. 'latest', 'v1.0')
	SourceTag string `json:"source_tag"`
	// Tag name in the new repo (defaults to source_tag if omitted)
	TagName string `json:"tag_name,omitempty"`
}

// 
type VmCommitEntity struct {
	CreatedAt string `json:"created_at"`
	Description string `json:"description,omitempty"`
	// The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree.
	GrandparentCommitId string `json:"grandparent_commit_id,omitempty"`
	Id string `json:"id"`
	// Whether this commit is publicly accessible (readable/restorable by anyone).
	IsPublic bool `json:"is_public"`
	Name string `json:"name"`
	// api key id.
	OwnerId string `json:"owner_id"`
	// The VM that this commit was created from, if any.
	ParentVmId string `json:"parent_vm_id,omitempty"`
}

// Tag information returned in list and get operations
type TagInfo struct {
	// The commit ID this tag currently points to
	CommitId string `json:"commit_id"`
	// When the tag was created
	CreatedAt string `json:"created_at"`
	// Optional description of what this tag represents
	Description string `json:"description,omitempty"`
	// The tag's unique identifier
	TagId string `json:"tag_id"`
	// The name of the tag
	TagName string `json:"tag_name"`
	// When the tag was last updated (moved to different commit or description changed)
	UpdatedAt string `json:"updated_at"`
}

// Request body for PUT /api/vm/{vm_id}/files
type VmWriteFileRequest struct {
	// File contents, base64-encoded.
	ContentB64 string `json:"content_b64,omitempty"`
	// Create parent directories if they don't exist.
	CreateDirs bool `json:"create_dirs,omitempty"`
	// File mode (e.g. 0644). Defaults to 0644 if omitted.
	Mode int32 `json:"mode,omitempty"`
	// Destination path on the VM.
	Path string `json:"path,omitempty"`
}

// Streams available for exec logging.
type VmExecLogStream string

const (
	VmExecLogStreamStdout VmExecLogStream = "stdout"
	VmExecLogStreamStderr VmExecLogStream = "stderr"
)

// Individual log entry describing emitted stdout/stderr chunk.
type VmExecLogEntry struct {
	// Base64-encoded bytes from stdout/stderr chunk.
	DataB64 string `json:"data_b64"`
	ExecId string `json:"exec_id,omitempty"`
	Stream VmExecLogStream `json:"stream"`
	Timestamp string `json:"timestamp"`
}

// Request body for `PATCH /vm/{vm_id}/label` (upsert) and `PUT /vm/{vm_id}/labels` (replace).  `labels` is **required** on both endpoints. Sending a body without the field deserializes to a 400 — this is deliberate: the previous `Option<HashMap<…>>` shape silently no-op'd PATCH and (worse) silently wiped every label on PUT. An empty map (`{ 'labels': {} }`) is still accepted as an explicit 'clear all' for PUT and an explicit 'no-op' for PATCH.
type LabelVmRequest struct {
	Labels map[string]string `json:"labels"`
}

// Response for GET /api/v1/vm/{vm_id}/metadata
type VmMetadataResponse struct {
	CreatedAt string `json:"created_at"`
	DeletedAt string `json:"deleted_at,omitempty"`
	GrandparentVmId string `json:"grandparent_vm_id,omitempty"`
	Ip string `json:"ip"`
	// RAM in MiB allocated to this VM at create-time.
	MemSizeMib int32 `json:"mem_size_mib"`
	OwnerId string `json:"owner_id"`
	ParentCommitId string `json:"parent_commit_id,omitempty"`
	State VmState `json:"state"`
	// vCPUs allocated to this VM at create-time.
	VcpuCount int32 `json:"vcpu_count"`
	VmId string `json:"vm_id"`
}

// Response body for `GET /api/v1/whoami`.  Identifies the principal (user + organization) behind the bearer token used for the request, plus minimal metadata about the API key itself.  The endpoint is read-only and requires only a valid API key — useful for answering questions like 'whose account does this key belong to?' without needing direct database access. Modeled after GitHub's `GET /user`.
type WhoamiResponse struct {
	ApiKey WhoamiApiKey `json:"api_key"`
	Org WhoamiOrg `json:"org"`
	User WhoamiUser `json:"user"`
}

// Request body for PATCH /api/v1/repositories/{repo_name}/visibility
type SetRepositoryVisibilityRequest struct {
	// Whether the repository should be publicly visible
	IsPublic bool `json:"is_public"`
}

// Request body for PATCH /api/v1/repositories/{repo_name}/tags/{tag_name}
type UpdateRepoTagRequest struct {
	// Optional new commit ID to move the tag to
	CommitId string `json:"commit_id,omitempty"`
	// Optional new description for the tag. Send `null` to clear.
	Description string `json:"description,omitempty"`
}

// Struct representing configuration options common to all VMs
type VmCreateVmConfig struct {
	// The disk size, in MiB.
	FsSizeMib int32 `json:"fs_size_mib,omitempty"`
	// The filesystem base image name. Currently, must be 'default'
	ImageName string `json:"image_name,omitempty"`
	// The kernel name. Currently, must be 'default.bin'
	KernelName string `json:"kernel_name,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	// The RAM size, in MiB.
	MemSizeMib int32 `json:"mem_size_mib,omitempty"`
	// How many vCPUs to allocate to this VM (and its children)
	VcpuCount int32 `json:"vcpu_count,omitempty"`
}

// Response body for new VM requests (new_root, from_commit, branch)
type NewVmResponse struct {
	VmId string `json:"vm_id"`
}

// Request body for POST /api/v1/vm/from_commit
// This is a union type — exactly one field should be set.
type FromCommitVmRequest struct {
	CommitId *string `json:"commit_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
	Ref *string `json:"ref,omitempty"`
}

// 
type VM struct {
	CreatedAt string `json:"created_at"`
	Labels map[string]string `json:"labels,omitempty"`
	OwnerId string `json:"owner_id"`
	State VmState `json:"state"`
	VmId string `json:"vm_id"`
}

// Request body for POST /api/v1/domains
type CreateDomainRequest struct {
	Domain string `json:"domain"`
	VmId string `json:"vm_id"`
}

// Request body for PATCH /api/v1/commit_tags/{tag_name}  For `description`: - Field absent from JSON → don't change the description - Field present as `null` → clear the description - Field present as `'text'` → set the description to 'text'
type UpdateTagRequest struct {
	// Optional new commit ID to move the tag to
	CommitId string `json:"commit_id,omitempty"`
	// Optional new description for the tag. Send `null` to clear an existing description.
	Description string `json:"description,omitempty"`
}

// 
type UploadBaseImageResponse struct {
	ImageName string `json:"image_name"`
	JobId string `json:"job_id"`
	Status string `json:"status"`
}

// 
type WhoamiUser struct {
	Email string `json:"email"`
	Id string `json:"id"`
	UserName string `json:"user_name"`
}

// 
type BaseImageStatusResponse struct {
	ErrorMessage string `json:"error_message,omitempty"`
	ImageName string `json:"image_name"`
	SizeMib int32 `json:"size_mib"`
	Status string `json:"status"`
}

// 
type ListBaseImagesResponse struct {
	Images []BaseImageInfo `json:"images"`
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total int64 `json:"total"`
}

// 
type NewRootRequest struct {
	VmConfig VmCreateVmConfig `json:"vm_config"`
}

// Request body for PATCH /api/vm/{vm_id}/disk
type VmResizeDiskRequest struct {
	// The new disk size in MiB. Must be strictly greater than the current size.
	FsSizeMib int32 `json:"fs_size_mib"`
}

// Response body for DELETE /api/vm/{vm_id}
type VmDeleteResponse struct {
	VmId string `json:"vm_id"`
}

// Response body for POST /api/v1/commit_tags
type CreateTagResponse struct {
	// The commit ID this tag points to
	CommitId string `json:"commit_id"`
	// The ID of the newly created tag
	TagId string `json:"tag_id"`
	// The name of the tag
	TagName string `json:"tag_name"`
}

// Request body for `POST /api/v1/deploy`.
type DeployRequest struct {
	// Git branch to clone (defaults to repo default branch).
	Branch string `json:"branch,omitempty"`
	// Optional project name (defaults to repo name).
	Name string `json:"name,omitempty"`
	// GitHub repository in `owner/repo` format.
	Repo string `json:"repo"`
	Settings interface{} `json:"settings,omitempty"`
}

// Tag information within a repository context
type RepoTagInfo struct {
	// The commit ID this tag currently points to
	CommitId string `json:"commit_id"`
	// When the tag was created
	CreatedAt string `json:"created_at"`
	// Optional description
	Description string `json:"description,omitempty"`
	// Full reference in image_name:tag format
	Reference string `json:"reference"`
	// The tag's unique identifier
	TagId string `json:"tag_id"`
	// The tag name
	TagName string `json:"tag_name"`
	// When the tag was last updated
	UpdatedAt string `json:"updated_at"`
}

// Response for exec log tail requests.
type VmExecLogResponse struct {
	// Returned log entries.
	Entries []VmExecLogEntry `json:"entries"`
	// True when the end of file was reached.
	Eof bool `json:"eof"`
	// Next byte offset to continue from.
	NextOffset int64 `json:"next_offset"`
}


// ── Params types for operations with query parameters ───────────────

// VmLogsParams holds optional query parameters.
type VmLogsParams struct {
	Offset *int64 `json:"offset,omitempty"`
	MaxEntries *int64 `json:"max_entries,omitempty"`
	Stream *string `json:"stream,omitempty"`
}

// UpdateVmStateParams holds optional query parameters.
type UpdateVmStateParams struct {
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
}

// ReadFileVmParams holds optional query parameters.
type ReadFileVmParams struct {
	Path *string `json:"path,omitempty"`
}

// ResizeVmDiskParams holds optional query parameters.
type ResizeVmDiskParams struct {
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
}

// CreateNewRootVmParams holds optional query parameters.
type CreateNewRootVmParams struct {
	WaitBoot *bool `json:"wait_boot,omitempty"`
}

// BranchByRefParams holds optional query parameters.
type BranchByRefParams struct {
	Count *int64 `json:"count,omitempty"`
}

// BranchByTagParams holds optional query parameters.
type BranchByTagParams struct {
	Count *int64 `json:"count,omitempty"`
}

// BranchVmParams holds optional query parameters.
type BranchVmParams struct {
	KeepPaused *bool `json:"keep_paused,omitempty"`
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
	Count *int64 `json:"count,omitempty"`
}

// DeleteVmParams holds optional query parameters.
type DeleteVmParams struct {
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
}

// BranchByVmParams holds optional query parameters.
type BranchByVmParams struct {
	KeepPaused *bool `json:"keep_paused,omitempty"`
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
	Count *int64 `json:"count,omitempty"`
}

// CommitVmParams holds optional query parameters.
type CommitVmParams struct {
	KeepPaused *bool `json:"keep_paused,omitempty"`
	SkipWaitBoot *bool `json:"skip_wait_boot,omitempty"`
}

// ListDomainsParams holds optional query parameters.
type ListDomainsParams struct {
	VmId *string `json:"vm_id,omitempty"`
}

// BranchByCommitParams holds optional query parameters.
type BranchByCommitParams struct {
	Count *int64 `json:"count,omitempty"`
}

